import Config

# Allow custom Logger metadata used by simulators and MqttBridge (removes Credo warnings)
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:device, :enabled, :duration_ms, :state, :topic, :action, :error]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :fleet_monitor, FleetMonitorWeb.Endpoint,
  # Note: The actual `http: [port:, ip:]` options are now set centrally in runtime.exs
  # so that $PORT is always respected and we get a clear startup message.
  # We keep dev-only flags here.
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "E7whikhv7by4ZluBG21SH5fJPYyoPjIjG48VGeRQ6OvGMlZ06LcvpIYxol7sZE3Q",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:fleet_monitor, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:fleet_monitor, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :fleet_monitor, FleetMonitorWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/fleet_monitor_web/router\.ex$",
      ~r"lib/fleet_monitor_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :fleet_monitor, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
