defmodule FleetMonitorWeb.Endpoint do
  @moduledoc """
  Phoenix Endpoint for the Fleet Console.

  Responsibilities:
  - Serve the LiveView WebSocket (`/live`) used by `FleetConsoleLive`.
  - Serve static assets (compiled JS/CSS, images, favicon).
  - Configure the signed session cookie (used by LiveView for flash, etc.).
  - Apply standard security plugs (CSRF via router, secure headers).

  Note on the console's custom layout:
  While the endpoint and router set up a normal Phoenix LiveView environment,
  the main console LiveView renders a custom full-width dark industrial UI
  instead of the standard `Layouts.app` wrapper. This was a deliberate Phase 3
  design decision to achieve the "control room" aesthetic (see `router.ex`
  and `fleet_console_live.ex` comments).

  The session is only signed (not encrypted) because we do not store sensitive
  data in it for this demo application.

  @phase 2 (generated) + Phase 3 customizations
  """

  use Phoenix.Endpoint, otp_app: :fleet_monitor
  require Mix

  # In development we deliberately disable HTTP caching for static assets (JS/CSS).
  # This means a normal browser refresh (Cmd/Ctrl + R) is always enough to pick up
  # changes to hooks in app.js (e.g. slider label updates, new UI behaviour).
  # No hard-refresh or "disable cache" dance is ever required for demo participants.
  # In production the far-future cache headers are used instead.
  @static_cache_control (if Mix.env() == :dev do
                           "no-cache, no-store, must-revalidate, max-age=0"
                         else
                           "public, max-age=31536000, immutable"
                         end)

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_fleet_monitor_key",
    signing_salt: "lMVQ/zv7",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :fleet_monitor,
    gzip: not code_reloading?,
    only: FleetMonitorWeb.static_paths(),
    raise_on_missing_only: code_reloading?,
    cache_control_headers: @static_cache_control

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug FleetMonitorWeb.Router
end
